### ISSUE TITLE
Position values not working

### ISSUE THREAD

**Issue by Just-another-pleb** [erfanjahanshahlo/node-red-contrib-pifacecad#2]
This is the most basic flow I can show:

```
[{"id":"fedeaebd.485938","type":"inject","z":"cc585130.29b7e8","name":"","topic":"","payload":"2,5:\"This is a test\"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1500,"y":80,"wires":[["3d749079.fb982"]]},{"id":"3d749079.fb982","type":"pfc_lcd","z":"cc585130.29b7e8","name":"Display","x":1790,"y":160,"wires":[]}]
```

I believe that should be line 2, position 5.
It shows on line 1, position 1.

**Comment by erfanjahanshahlo** [comment]
Probably because the text is longer than the lcd display in this case. You see that you said line 2, col 5, and 14 character text, but if we subtract 5 from 16, 11 characters remain. Please try a shorter text. if not working please let know(in this post).

**Comment by Just-another-pleb** [comment]
Putting aside the size of the display and the position not working, I decided to send messages only starting at 1,1.   (See more at bottom)

It hasn't got to the stage where display positioning is crucial anyway.

The messages weren't that long.
Something like:
S5 requesting power
(Alas I can't do length calculations on this screen as the spaces are proportional.)
Length is 17.
The display is 16.
So all I saw were the first 16 characters of the message.

That got me asking/thinking:   Why doesn't it wrap to the second line?  (Rhetorical)

So to really test this I made a stupidly long message.
This:
> This is a test to see what happens with long strings

I sent it to the display.

I saw the first 16 characters then on the second line I saw the end of message.
> This is a test t
> long strings

So there is another *gremlin* in there I fear.

(Extra bit.)
Going on from you saying
> Probably because the text is longer than the lcd display in this case

2,2:"Hello"
Line 1, column 1.   Hello.   :(
Sorry.

**Comment by erfanjahanshahlo** [comment]
im updated the node.
for write in row 1 and column 1 and write hello send below code.
```1,1:hello```

**Comment by Just-another-pleb** [comment]
I think the meaning was lost in translation of what I wrote.   Sorry.

If I send:
2,2:"Hello"
I get "Hello" at position 1 of line 1.
Not position 2 of line 2.

I will install the new node as soon as I can and test it and report back.
I'm guessing not many people would be doing much other than 1,1: messages.

Oh, have you thought about the suggestion if there is no leading position data, it defaults to 1,1?

**Comment by erfanjahanshahlo** [comment]
No If you do not specify a position, the node will make an error and you will have to specify it by default with a JavaScript code in the function node and the JavaScript code will automatically determine the position. Please reply as soon as you are able to update the node, I have solved the problem and if you submit the following code now the text will be displayed in the same situation. If you can't write Javascript code let me know I will write the code for you.
```1,1:HELLO```

**Comment by Just-another-pleb** [comment]
Ok.  Updated.

> No If you do not specify a position, the node will make an error and you will have to specify it by default with a JavaScript code in the function node and the JavaScript code will automatically determine the position. Please reply as soon as you are able to update the node, I have solved the problem and if you submit the following code now the text will be displayed in the same situation. If you can't write Javascript code let me know I will write the code for you.
1,1:HELLO

This is becoming more confusing.

The node is a great idea.  Display messages on the PiFace CAD hat LCD.

However:
1 - If the message does not have a prefix of the position the node spits an error.
It is/was only a SUGGESTION that you put some code so if there isn't this prefix the node automatically uses 1,1 rather than generating an error.

2 - If the message is to be at (say) line 2 position 2 (poor example, but) the message is prefixed with 2,2
But it still doesn't work.

Your example of 1,1:"Hello" works.   It did originally.    The first problem I raised was because I am stupid and didn't put the 1,1: at the start of the message.
Once I worked that out (or realised it was needed) it started working.
But that was when things were simple and I simply wanted the message at 1,1.

Like I have said:  If the message is to be written anywhere else:  The node still puts it at 1,1

This code:
```
[{"id":"78add225.b3f074","type":"inject","z":"cc585130.29b7e8","name":"","topic":"","payload":"2,2:Hello","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1460,"y":160,"wires":[["3d749079.fb982"]]},{"id":"a0ab737a.41d5a8","type":"inject","z":"cc585130.29b7e8","name":"","topic":"","payload":"1,1:Hello","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1460,"y":300,"wires":[["3d749079.fb982","c4db9353.f211e8"]]},{"id":"3d749079.fb982","type":"pfc_lcd","z":"cc585130.29b7e8","name":"Display","x":1650,"y":300,"wires":[]}]
```

Both messages display at the same position on the screen.

**Comment by erfanjahanshahlo** [comment]
Thanks for your suggestions. I'll think about them.

**Comment by Just-another-pleb** [comment]
I found the problem:

Your code should be/read:
```
import pifacecad
import sys

try:
    text_splited = sys.argv[1].split(":")
    rowcol = text_splited[0].split(",")
    text = text_splited[1]
    text = text.replace("#/@$%", " ")
except:
    raise TypeError("The sended text is not correct")

cad = pifacecad.PiFaceCAD()
cad.lcd.backlight_on()
cad.lcd.cursor_off()
cad.lcd.set_cursor (int(rowcol[1]), int(rowcol[0]))
if (text):
    cad.lcd.write(unicode(text))
else:
    cad.lcd.clear()
```

Where you have:
```
cad.lcd.set_cursor = (int(rowcol[1]), int(rowcol[0]))
```

The `=` sign is not needed and therefore causes the position to not work.

I tested it and put in a message:
`2,5:"This is a test" and it is on row 2, column 5.
(Though longer than the display, it puts the message where it needs to be as per the supplied values)

**Comment by Just-another-pleb** [comment]
And if you wanted to be really smart, you could use this code:
```
import pifacecad
import sys

try:
    text_splited = sys.argv[1].split(":")
    rowcol = text_splited[0].split(",")
    text = text_splited[1]
    text = text.replace("#/@$%", " ")
except:
    raise TypeError("The sended text is not correct")

cad = pifacecad.PiFaceCAD()
cad.lcd.backlight_on()
cad.lcd.cursor_off()
cad.lcd.set_cursor (int(rowcol[1])-1, int(rowcol[0])-1)
if (text):
#    cad.lcd.write(unicode(text))
    cad.lcd.write(text)
    cad.lcd.move_right()
    cad.lcd.move_left()
    cad.lcd.see_cursor()
#    cad.lcd.write(unicode(text))
else:
    cad.lcd.clear()
```

This code differs because the code above is ZERO counting.
So the top left is 0,0
This new code the top left is 1,1

Just as an alternative.

**Comment by erfanjahanshahlo** [comment]
My dear friend, I was using this Architecture at first, but after you got the error, I changed the code because I wasn't have board. I will be updating it soon and since I don't have much time left.
