### ISSUE TITLE
Where are the switch files?

### ISSUE THREAD

**Issue by Just-another-pleb** [erfanjahanshahlo/node-red-contrib-pifacecad#3]
In the `README` there is this:

-node-red-pifacecad-lcd<br/>
---package.json<br/>
---pfc_lcd.py<br/>
---pfc_lcd.js<br/>
---pfc_lcd.html<br/>
---pfc_switch.py<br/>
---pfc_switch.js<br/>
---pfc_switch.html<br/>

But I can't see any `pfc_switch`.... (anything)

**Comment by erfanjahanshahlo** [comment]
Thank you for your attention. Was corrected.
