### ISSUE TITLE
Display light being turned off between writing messages

### ISSUE THREAD

**Issue by Just-another-pleb** [erfanjahanshahlo/node-red-contrib-pifacecad#4]
I am wanting to send messages to the display.

The light is on.

But when I send the second message the display blinks off quickly and I don't know why.

Any thoughts?

Further investigation shows sending a message also CLEARS the screen.

I would prefer the screen only clears when I send a "clear screen" command.

That could be part of the problem.

**Comment by erfanjahanshahlo** [comment]
This does not happen. Can you record video?

**Comment by Just-another-pleb** [comment]
Not easily.

Sorry, I shall try to do it, but please don't expect a fast reply.

This is just a slight `bump` for me prototyping a new project which will be using a different display and different node.

I am working with what I have for concept testing.   Though you saying it doesn't happen with yours is reassuring that things for me will work out for the better.

(Off topic and sorry)  I did get the cursor positioning working (my other "bugs" I mentioned to you a long time ago)
Was working and has suddenly stopped.   I think there is something else going on.
Do you want me to leave this open (ongoing) or close it and when I get the video I will then bring it up again?
As I said, I am not sure I am wanting to spend too much more time on this - yes, I know I brought it up - but as explained:  This was for testing a concept which I think is good enough to take to the next stage.

**Comment by erfanjahanshahlo** [comment]
It is better to continue the project you are creating without nodered because no project has succeeded with drag and drop, and if it is possible to use a normal character lcd, it would be better and you could use my lcd library. The problem is that I can not access the pifacecad board and try it myself because I am in Iran and this board is not for sale anywhere in Iran.

**Comment by Just-another-pleb** [comment]
No problems.
